const fs = require("fs");
const path = require("path");

module.exports = {
  config: {
    name: "🔰𝗥𝗮𝗵𝗮𝘁_𝗕𝗼𝘁🔰",
    aliases: [],
    version: "1.0",
    author: "Generated by ChatGPT",
    countDown: 5,
    role: 2,
    shortDescription: "মেনশন করো",
    longDescription: "!Khan @user — মেনশন করা ",
    category: "fun",
    guide: {
      en: "{pn} @mention"
    }
  },

  onStart: async function ({ api, event, args, Users }) {
    // মেনশন আছে কি না চেক
    if (!event.mentions || Object.keys(event.mentions).length === 0) {
      return api.sendMessage("কোন একটা খানকি-কে মেনশন করো Boss 🙂", event.threadID, event.messageID);
    }

    try {
      // প্রথম মেনশন নেওয়া
      const mentionID = Object.keys(event.mentions)[0];
      const mentionName = event.mentions[mentionID] || (await Users.getName(mentionID));

      // ভিডিওর লোকাল ফাইল পাথ (আপনার ভিডিওর নাম অনুযায়ী বদলান)
      const videoPath = path.join(__dirname, "..", "voice", "khan.mp4");

      if (!fs.existsSync(videoPath)) {
        return api.sendMessage(
          `${mentionName} খানকির পোলা🫦মাদারচোদ💦তোর জন্য ভয়েসটা😏Rahat বসের বদলে আমি চুদে দিলাম💋💦\n(⚠️ অডিও ফাইল পাওয়া যায়নি: ${videoPath})`,
          event.threadID,
          event.messageID
        );
      }

      // মেসেজ পাঠানো
      return api.sendMessage(
        {
          body: `${mentionName} খানকির পোলা🫦মাদারচোদ💦তোর জন্য ভয়েসটা😏Rahat বসের বদলে আমি চুদে দিলাম💋💦`,
          mentions: [{ tag: mentionName, id: mentionID }],
          attachment: fs.createReadStream(videoPath)
        },
        event.threadID,
        event.messageID
      );
    } catch (err) {
      console.error("Error in Khan command:", err);
      return api.sendMessage(
        "কোথাও ত্রুটি হয়েছে — অডিও পাঠানো যায়নি।",
        event.threadID,
        event.messageID
      );
    }
  }
};
